name: Deploy Application

on:
  push:
    branches:
      - master

jobs:
  create-deployment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Complile CSS and Javascript
        run: |
          npm install
          npm run prod

      - name: configure PHP 8.0
        uses: shivammathur/setup-php@master
        with:
          php-version: 8.0
          extentions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install composer dependencies
        run: composer install --no-dev --no-interaction --prefer-dist

      - name: Create deployment artifacts
        run: tar -czf app.tar.gz --exclude=*.git --exclude=node_modules *
